version: "3.6"

services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:80"
    volumes:
      - ./orchestrator:/usr/local/orchestrator
    environment:
      ORCHESTRATOR_PORT: 80
      NODE_ENV: "production"
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      APP_SERVICE_BASE_URL: ${APP_SERVICE_BASE_URL}
    volumes:
      - ./orchestrator:/usr/local/orchestrator
  app-services:
    build: ./services/app
    ports:
      - "4002:4002"
    volumes:
      - ./services/app:/usr/local/app
    environment:
      NODE_ENV: "production"
      APP_SERVICES_PORT: 4002
      ADMIN_SECRETS: ${ADMIN_SECRETS}
      DATABASE_URL: ${DATABASE_URL}
  user-service:
    build: ./services/users
    ports:
      - "4001:4001"
    environment:
      ENV USER_PORT: 4001
      NODE_ENV: "production"
      USER_DATABASE_URI: ${USER_DATABASE_URI}
      ADMIN_SECRETS: ${ADMIN_SECRETS}
    volumes:
      - ./services/users:/usr/local/user
